export const GET_SHOW_START = 'GET_SHOW_START';
export const GET_SHOW_SUCCESS = 'GET_SHOW_SUCCESS';
export const GET_SHOW_FAIL = 'GET_SHOW_FAIL';
export const GET_SHOW_INIT = 'GET_SHOW_INIT';

export const GET_EPISODE_START = 'GET_EPISODE_START';
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
export const GET_EPISODE_FAIL = 'GET_EPISODE_FAIL';
export const GET_EPISODE_INIT = 'GET_EPISODE_INIT';

export const CLEAR_EPISODE_DATA = 'CLEAR_EPISODE_DATA';
